from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_rule
from . import product_product
from . import product_pricelist
from . import product_pricelist_item
from . import product_brand
from . import product_series
from . import product_template
from . import stock_route
from . import product_supplierinfo
from . import sale_order
from . import sale_order_line
from . import delivery_type
from . import delivery_floor
from . import delivery_method
from . import product_type
from . import res_company
from . import res_config_settings
from . import sales_projects
from . import sales_projects_apartment
from . import res_partner
from . import res_users
from . import purchase_order
from . import purchase_order_line
from . import crm_lead
from . import account_move
from . import account_move_line
from . import account_analytic_account
from . import account_invoice_report
from . import mrp_capacity_booking
from . import ir_attachment
from . import strai_campaign
from . import sale_advance_payment_inv
from . import winner_customer
from . import account_payment
from . import product_pricelist_builder_discount_matrix
from . import res_partner_builder_discount_matrix
from . import winner_catalogue
from . import purchase_report
from . import account_analytic_line
from . import stock_quant
from . import maintenance_equipment
from . import maintenance_request
