{
    'name': "Strai",
    'summary': "Extension module for Strai Kjøkken",
    'description': "Contains necessary model extensions, new models and flow logic",
    'author': "Strai Kjøkken AS",
    'website': "https://www.strai.no",
    'category': 'Customization',
    'version': '17.0.0.0.7',
    'depends': ['stock', 'product', 'sale', 'crm', 'purchase', 'sale_purchase', 'account', 'web', 'sale_purchase_inter_company_rules',
                'trunk', 'trunk_queue', 'purchase_requisition', 'web_notify', 'account_batch_payment', 'sale_project', 'web_datetime_widget', 'maintenance'],
    'data': [
        'security/sales_projects_security.xml',
        'security/sales_projects_apartment_security.xml',
        'security/campaign_security.xml',
        'security/ir.model.access.csv',
        'security/real_users_security.xml',
        'views/stock_picking_views.xml',
        'views/stock_move_line_views.xml',
        'views/product_pricelist_views.xml',
        'views/product_views.xml',
        'views/product_template_views.xml',
        'views/stock_route_views.xml',
        'views/sale_order_views.xml',
        'views/product_type_views.xml',
        'views/delivery_type_views.xml',
        'views/delivery_floor_views.xml',
        'views/delivery_method_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_company_views.xml',
        'views/sales_projects_views.xml',
        'views/strai_campaign_views.xml',
        'views/account_payment_views.xml',
        'report/report_saleorder_document.xml',
        'report/template_followup_report_inherit.xml',
        'wizard/winner_ref_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/purchase_order_views.xml',
        'wizard/crm_lead_lost_views.xml',
        'views/crm_lead_views.xml',
        'views/account_analytic_account_views.xml',
        'data/mail_template.xml',
        'data/ir_cron_data.xml',
        'views/ir_attachment_views.xml',
        'views/ir_views.xml',
        'wizard/sale_invoice_views.xml',
        'views/account_move_views.xml',
        'wizard/mail_compose_message_view.xml',
        'report/report_purchaseorder_doc_inherit.xml',
        'views/res_user_views.xml',
        'views/product_supplierinfo_views.xml',
        'views/product_pricelist_builder_discount_matrix_views.xml',
        'views/res_partner_builder_discount_matrix_views.xml',
        'views/winner_catalogue_views.xml',
        'views/stock_warehouse_views.xml',
        'views/maintenance_equipment_views.xml',
        'views/maintenance_request_views.xml',
    ],
    "assets": {
        "web.assets_backend": [
            "strai/static/src/scss/strai_attachments.scss",
            "strai/static/src/js/widgets/switch_company_menu.js",
            "strai/static/src/js/strai_drag_attachement.js",
            "strai/static/src/js/attachment_preview.js",
            "strai/static/src/xml/drag_attachment_template.xml",
            "strai/static/src/css/styles.css",
            "strai/static/src/xml/sale_dashboard.xml",
            "strai/static/src/xml/sale_listview.xml",
            "strai/static/src/xml/purchase_order_dashboard.xml",
            "strai/static/src/js/sale_dashboard.js",
            "strai/static/src/js/sale_listview.js",
            
        ],
    },
    "external_dependencies": {
        "python": ['holidays'],
    },
    'license': "LGPL-3"
}
