import datetime

from ..models.sale_order import SaleOrder

# constants
winnerorder_factory = {'orders': [{
    "winner_lead_ref": "1/544049",
    "winner_reference": "544049/1/4",
    "version": 1,
    "winnerfile_id": 55437,
    "crm_name": "Winner 544049  Vågsnes, Tormod",
    "order_version": True,
    "sale_reference": "",
    "external_sales_order_number": None,
    "customer": {
        "name": " Strai Kjøkken Arendal",
        "update": True,
        "street": "0",
        "street2": "",
        "city": "",
        "zip": None,
        "country": "NO",
        "phone": "37022910",
        "mobile": None,
        "reference": "1/100141",
        "winner_reference": "1/100141/544049/1/4",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "1/100141"
    },
    "customer_shipping": {
        "name": " Vågsnes, Tormod",
        "update": True,
        "street": "Rørendal Strandvei tomt 1",
        "street2": "",
        "city": "FÆRVIK",
        "zip": "4818",
        "country": "NO",
        "phone": None,
        "mobile": None,
        "reference": "1/100141",
        "winner_reference": "1/100141/544049/1/4",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "1/100141"
    },
    "customer_invoice": {
        "name": " Strai Kjøkken Arendal",
        "update": True,
        "street": "Postboks 1580 Stoa",
        "street2": "",
        "city": "ARENDAL",
        "zip": "4857",
        "country": "NO",
        "phone": "37022910",
        "mobile": None,
        "reference": "1/100141",
        "winner_reference": "1/100141/544049/1/4",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "1/100141"
    },
    "customer_reference": "1/100141",
    "order_number": "1/544049/1/4",
    "sales_company": 1,
    "company": 1,
    "sales_email": "",
    "sales_phone": "",
    "tags": [
        "Tromsø"
    ],
    "quotation_total_price": 58951.12,
    "order_lines": [
        {
            "product": {
                "name": "Møbler",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "SI280050 Løs dekkside 264,8x58,7 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 2139.57,
                "sale_price": 2139.58,
                "cost_price": 0.0,
                "total_price": 2674.47,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 20
        },
        {
            "product": {
                "name": "SK090001 Benkeskap 90 cm m/2 dører",
                "reference": "StraiBenkeskap",
                "update": True,
                "description": "",
                "catalogue_price": 3527.01,
                "sale_price": 3527.02,
                "cost_price": 0.0,
                "total_price": 4408.77,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Skap/Benkeskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 30
        },
        {
            "product": {
                "name": "SI280050 Løs dekkside 264,8x58,7 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 2139.57,
                "sale_price": 2139.58,
                "cost_price": 0.0,
                "total_price": 2674.47,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 40
        },
        {
            "product": {
                "name": "FO015700 Foringslist 15 cm H:249,8 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 569.55,
                "sale_price": 569.54,
                "cost_price": 0.0,
                "total_price": 711.93,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 50
        },
        {
            "product": {
                "name": "OS100701 Åpent overskap 100 cm H:124,9 cm, finert",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 5244.77,
                "sale_price": 5244.78,
                "cost_price": 0.0,
                "total_price": 6555.97,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 60
        },
        {
            "product": {
                "name": "FO015001 Foringslist 15 cm H:72 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 212.61,
                "sale_price": 212.62,
                "cost_price": 0.0,
                "total_price": 265.77,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 70
        },
        {
            "product": {
                "name": "SI072000 Løs dekkside 72x31,5 cm ",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 551.18,
                "sale_price": 551.18,
                "cost_price": 0.0,
                "total_price": 688.98,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 71
        },
        {
            "product": {
                "name": "GO060003 Overskap 60 cm Dybde 56,5 cm (H:72 cm)",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 2849.54,
                "sale_price": 2849.54,
                "cost_price": 0.0,
                "total_price": 3561.93,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 80
        },
        {
            "product": {
                "name": "OS090701 Åpent overskap 90 cm H:124,9 cm, finert",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 4976.60,
                "sale_price": 4976.61,
                "cost_price": 0.0,
                "total_price": 6220.76,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 90
        },
        {
            "product": {
                "name": "OS100701 Åpent overskap 100 cm H:124,9 cm, finert",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 5244.77,
                "sale_price": 5244.78,
                "cost_price": 0.0,
                "total_price": 6555.97,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 100
        },
        {
            "product": {
                "name": "SO000001 Sokkelklips, pose a 10 stk.",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 69.20,
                "sale_price": 69.2,
                "cost_price": 0.0,
                "total_price": 259.50,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 3.0000,
            "line_type": 1,
            "item_position": 110
        },
        {
            "product": {
                "name": "SB200015 Sokkelbein plast, komplett m/holder ",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 26.13,
                "sale_price": 26.13,
                "cost_price": 0.0,
                "total_price": 195.97,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 6.0000,
            "line_type": 1,
            "item_position": 5010
        },
        {
            "product": {
                "name": "SO240000 Sokkelbord 240 cm H:15 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 621.78,
                "sale_price": 621.78,
                "cost_price": 0.0,
                "total_price": 1554.45,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": True,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 2.0000,
            "line_type": 1,
            "item_position": 5020
        },
        {
            "product": {
                "name": "Benkeplater",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "B2 Benkeplate 301-620 mm",
                "reference": "B2",
                "update": True,
                "description": "",
                "catalogue_price": 1213.59,
                "sale_price": 1213.59,
                "cost_price": 0.0,
                "total_price": 1450.24,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "605",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All/Benkeplater/Heltre- og laminatplater",
                "brand": "Foss Plater",
                "series": ""
            },
            "quantity": 0.9560,
            "line_type": 1,
            "item_position": 5000
        },
        {
            "product": {
                "name": "ABS1031 Tillegg ABS1031 Diego Oak 4167 WH",
                "reference": "ABS1031",
                "update": True,
                "description": "",
                "catalogue_price": 332.32,
                "sale_price": 332.32,
                "cost_price": 0.0,
                "total_price": 397.12,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "605",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All/Benkeplater/Heltre- og laminatplater",
                "brand": "Foss Plater",
                "series": ""
            },
            "quantity": 0.9560,
            "line_type": 1,
            "item_position": 5001
        },
        {
            "product": {
                "name": "LT03ABS Endebelisting laminat",
                "reference": "LT03ABS",
                "update": True,
                "description": "",
                "catalogue_price": 240.45,
                "sale_price": 240.45,
                "cost_price": 0.0,
                "total_price": 300.56,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "605",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All/Benkeplater/Heltre- og laminatplater",
                "brand": "Foss Plater",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 5002
        },
        {
            "product": {
                "name": "LT03ABS Endebelisting laminat",
                "reference": "LT03ABS",
                "update": True,
                "description": "",
                "catalogue_price": 240.45,
                "sale_price": 240.45,
                "cost_price": 0.0,
                "total_price": 300.56,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "605",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All/Benkeplater/Heltre- og laminatplater",
                "brand": "Foss Plater",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 5003
        },
        {
            "product": {
                "name": "Hvitevarer",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "KUT5NF26W FRYSESKAP: Frys, 253 L, 1860 mm, FrostFree, F, P10 kontroll, Elektronisk LCD innvendig, 41 dB(A)/C, Hvit",
                "reference": "KUT5NF26W",
                "update": True,
                "description": "",
                "catalogue_price": 13134.00,
                "sale_price": 13134.0,
                "cost_price": 0.0,
                "total_price": 16417.50,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "122",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All/Hvitevarer",
                "brand": "Electrolux",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 10
        },
        {
            "product": {
                "name": "Tilbehør",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "343276-11 Knopp como -26 matt svart",
                "reference": "343276-11",
                "update": True,
                "description": "",
                "catalogue_price": 39.00,
                "sale_price": 39.0,
                "cost_price": 0.0,
                "total_price": 146.25,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "164",
                "product_type": "product",
                "direct_supplier": True,
                "product_category": "All",
                "brand": "Beslag Design",
                "series": ""
            },
            "quantity": 3.0000,
            "line_type": 1,
            "item_position": 4500
        },
        {
            "product": {
                "name": "Miljøgebyrer",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "Miljøgebyr KUT5NF26W",
                "reference": "Miljøgebyr",
                "update": True,
                "description": "",
                "catalogue_price": 88.00,
                "sale_price": 88.0,
                "cost_price": 88.00,
                "total_price": 110.00,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "122",
                "product_type": "Service",
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 9990
        },
        {
            "product": {
                "name": "Frakt",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "Frakt",
                "reference": "Frakt",
                "update": True,
                "description": "",
                "catalogue_price": 2800.00,
                "sale_price": 2800.00,
                "cost_price": 0.0,
                "total_price": 3500.0000,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "Service",
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 1.0,
            "line_type": 1,
            "item_position": 9970
        }
    ]
}]}
winnerorder_shop = {'orders': [{
    "winner_lead_ref": "9/59070",
    "winner_reference": "59070/1/27",
    "version": 3,
    "winnerfile_id": 55438,
    "crm_name": "Winner 59070  RL Entreprenør",
    "order_version": False,
    "sale_reference": "",
    "external_sales_order_number": None,
    "customer": {
        "name": " RL Entreprenør",
        "update": True,
        "street": "Tollbodgata 6",
        "street2": "",
        "city": "KRISTIANSAND S",
        "zip": "4611",
        "country": "NO",
        "phone": None,
        "mobile": "41267260",
        "reference": "9/2002212733",
        "winner_reference": "9/2002212733/59070/1/27",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "9/2002212733"
    },
    "customer_shipping": {
        "name": " RL Entreprenør",
        "update": True,
        "street": "Spangereidveien 4 - Leilighet 4",
        "street2": "",
        "city": "LINDESNES",
        "zip": "4520",
        "country": "NO",
        "phone": None,
        "mobile": "41267260",
        "reference": "9/2002212733",
        "winner_reference": "9/2002212733/59070/1/27",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "9/2002212733"
    },
    "customer_invoice": {
        "name": " RL Entreprenør",
        "update": True,
        "street": "Tollbodgata 6",
        "street2": "",
        "city": "KRISTIANSAND S",
        "zip": "4611",
        "country": "NO",
        "phone": None,
        "mobile": "41267260",
        "reference": "9/2002212733",
        "winner_reference": "9/2002212733/59070/1/27",
        "vat": "",
        "email": "",
        "is_company": False,
        "address_type": False,
        "website": "",
        "winner_customer_id": "9/2002212733"
    },
    "customer_reference": "9/2002212733",
    "order_number": "9/59070/1/27",
    "sales_company": 9,
    "company": 9,
    "sales_email": "kjell.rune@strai.no",
    "sales_phone": "+47 474 88 062",
    "tags": [
        "Dalen"
    ],
    "quotation_total_price": 4683.00,
    "order_lines": [
        {
            "product": {
                "name": "Møbler",
                "reference": None,
                "update": False,
                "description": None,
                "catalogue_price": 0.0,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": False,
                "purchased": False,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": None,
                "purchase_unit": None,
                "supplier_code": None,
                "product_type": None,
                "direct_supplier": False,
                "product_category": None,
                "brand": None,
                "series": None
            },
            "quantity": 0.0,
            "line_type": 3,
            "item_position": 0
        },
        {
            "product": {
                "name": "SK040001 Benkeskap 40 cm m/dør",
                "reference": "StraiBenkeskap",
                "update": True,
                "description": "",
                "catalogue_price": 1721.94,
                "sale_price": 1119.25,
                "cost_price": 0.0,
                "total_price": 1399.06,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": False,
                "product_category": "All/Møbler/Skap/Benkeskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 10
        },
        {
            "product": {
                "name": "OS040002 Overskap 40 cm m/dør H:72 cm",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 1645.26,
                "sale_price": 1069.42,
                "cost_price": 0.0,
                "total_price": 1336.77,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": False,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 20
        },
        {
            "product": {
                "name": "OS050002 Overskap 50 cm m/dør H:72 cm",
                "reference": "StraiOverskap",
                "update": True,
                "description": "",
                "catalogue_price": 1409.31,
                "sale_price": 916.05,
                "cost_price": 0.0,
                "total_price": 1145.06,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": False,
                "product_category": "All/Møbler/Skap/Overskap",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 30
        },
        {
            "product": {
                "name": " Har front fra tidligere bestilling. Høyrehengslet",
                "reference": "Strai",
                "update": True,
                "description": "",
                "catalogue_price": 0.00,
                "sale_price": 0.0,
                "cost_price": 0.0,
                "total_price": 0.0,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": False,
                "product_category": "All",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 0.0,
            "line_type": 2,
            "item_position": 31
        },
        {
            "product": {
                "name": "SI197050 Løs dekkside 196,8x58,7 cm",
                "reference": "StraiTilbehør",
                "update": True,
                "description": "",
                "catalogue_price": 987.22,
                "sale_price": 641.69,
                "cost_price": 0.0,
                "total_price": 802.11,
                "sold": True,
                "purchased": True,
                "volume": 0.0,
                "weight": 0.0,
                "manufacturing_time": 0.0,
                "delivery_time": 0.0,
                "sale_unit": "Stk",
                "purchase_unit": "Stk",
                "supplier_code": "1000",
                "product_type": "consu",
                "direct_supplier": False,
                "product_category": "All/Møbler/Tilbehør",
                "brand": "Strai Kjøkken",
                "series": ""
            },
            "quantity": 1.0000,
            "line_type": 1,
            "item_position": 40
        }
    ]
}]}

# sale order lines
order_lines = [
    {
        "product": {
            "name": "FancyProductNoSeries",
            "reference": "FancyProductNoSeries",
            "update": True,
            "description": "",
            "catalogue_price": 1000.0,
            "sale_price": 1000.0,
            "cost_price": 0.0,
            "total_price": 1250.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "fancy",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 0
    },
    {
        "product": {
            "name": "FancyProductFancy",
            "reference": "FancyProductFancy",
            "update": True,
            "description": "",
            "catalogue_price": 1000.0,
            "sale_price": 1000.0,
            "cost_price": 0.0,
            "total_price": 1250.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "fancy",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 2
    },
    {
        "product": {
            "name": "FancyProductStove",
            "reference": "FancyProductStove",
            "update": True,
            "description": "",
            "catalogue_price": 1000.0,
            "sale_price": 1000.0,
            "cost_price": 0.0,
            "total_price": 1250.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "fancy",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 3
    },
    {
        "product": {
            "name": "FancyProductRefrigerator",
            "reference": "FancyProductRefrigerator",
            "update": True,
            "description": "",
            "catalogue_price": 1000.0,
            "sale_price": 1000.0,
            "cost_price": 0.0,
            "total_price": 1250.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "fancy",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 4
    },
    {
        "product": {
            "name": "MediocreProductNoSeries",
            "reference": "MediocreProductNoSeries",
            "update": True,
            "description": "",
            "catalogue_price": 800.0,
            "sale_price": 800.0,
            "cost_price": 0.0,
            "total_price": 1000.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "mediocre",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 5
    },
    {
        "product": {
            "name": "MediocreProductMediocre",
            "reference": "MediocreProductMediocre",
            "update": True,
            "description": "",
            "catalogue_price": 800.0,
            "sale_price": 800.0,
            "cost_price": 0.0,
            "total_price": 1000.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "mediocre",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 6
    },
    {
        "product": {
            "name": "MediocreProductFreezer",
            "reference": "MediocreProductFreezer",
            "update": True,
            "description": "",
            "catalogue_price": 800.0,
            "sale_price": 800.0,
            "cost_price": 0.0,
            "total_price": 1000.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "mediocre",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 7
    },
    {
        "product": {
            "name": "CheapProductNoSeries",
            "reference": "CheapProductNoSeries",
            "update": True,
            "description": "",
            "catalogue_price": 700.0,
            "sale_price": 700.0,
            "cost_price": 0.0,
            "total_price": 875.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "cheap",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 8
    },
    {
        "product": {
            "name": "CheapProductCheap",
            "reference": "CheapProductCheap",
            "update": True,
            "description": "",
            "catalogue_price": 700.0,
            "sale_price": 700.0,
            "cost_price": 0.0,
            "total_price": 875.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "cheap",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 9
    },
    {
        "product": {
            "name": "Nobrand",
            "reference": "Nobrand",
            "update": True,
            "description": "",
            "catalogue_price": 700.0,
            "sale_price": 700.0,
            "cost_price": 0.0,
            "total_price": 875.0,
            "sold": True,
            "purchased": True,
            "volume": 0.0,
            "weight": 0.0,
            "manufacturing_time": 0.0,
            "delivery_time": 0.0,
            "sale_unit": "Stk",
            "purchase_unit": "Stk",
            "supplier_code": "1",
            "product_type": "product",
            "direct_supplier": False,
            "product_category": "All",
            "brand": "",
            "series": ""
        },
        "quantity": 1.0000,
        "line_type": 1,
        "item_position": 0
    }
]

# permissions
def permission_odoobot_allcompanies(env):
    odoobot = env['res.users'].search([('name', '=', 'OdooBot'), ('active', 'in', [True, False])])
    odoobot.company_ids = env['res.company'].search([])

def create_customer(env):
    customer = env['res.partner'].create({
        'name': 'Good Customer'
    })
    return customer

def create_suppliers(env):
    supplier_fancy = env['res.partner'].create({'name': 'FancySupplier', 'ref': '1'})
    supplier_mediocre = env['res.partner'].create({'name': 'MediocreSupplier', 'ref': '2'})
    supplier_cheap = env['res.partner'].create({'name': 'CheapSupplier', 'ref': '3'})
    return supplier_fancy, supplier_mediocre, supplier_cheap

def write_saleorder_defaults(saleorder):
    saleorder.remarks = 'test remarks'
    saleorder.external_sales_order_no = 'SO2325127'
    saleorder.product_type_id = 1
    saleorder.order_type = 'standard'
    saleorder.commitment_date = datetime.datetime(2023, 2, 1)
    saleorder.delivery_phone_one = '47473636'
    saleorder.delivery_method_id = 1
    saleorder.delivery_type_id = 1
    saleorder.delivery_floor_id = 1

def create_saleorder_lines(saleorder: SaleOrder, order_version):
    for order_line in order_lines:
        saleorder._create_sale_order_line(saleorder, order_version, order_line)
